### PR TITLE
Made the win message look more fancy

### PR DESCRIPTION
**Pull request by TheRealPear**
We're all in an era where most servers add a strikethrough to lines that separate important messages from chat. If you don't know what I'm talking about, here's a before and after picture: http://imgur.com/a/LRAbH

### CODE REVIEW

**Comment by FactoDoesStuff** [comment]
Since hazry's win messages are ugly and make me want to puke, I give this a +1!

**Comment by tjhubz** [comment]
Remove all of the space before the winning team and the congrats message, it will look better.

**Comment by TheRealPear** [comment]
@tjhubz I'll see what I can do

**Comment by TheRealPear** [comment]
@tjhubz The spaces are removed 👍

**Comment by tjhubz** [comment]
Update screenshots :)

**Comment by TheRealPear** [comment]
@tjhubz Too lazy.

**Pull request merged**
