### PR TITLE
New win messages.

### PR DESCRIPTION
**Pull request by HazryG**
Says the winning team with no grammar issues (like before) and a message depending on what team you're on; winning, losing, or spectator. Looks a lot tidier than the old win message I made imo.

### CODE REVIEW

**Comment by HazryG** [comment]
Fixed an issue :D

**Comment by tjhubz** [comment]
Post photos :)

**Comment by HazryG** [comment]
Pretty sure they were active on Draem's Infection test server but I'm not sure if he updated it. I can get some photos of them tomorrow (2am rn)

**Comment by HazryG** [comment]
Winning message


Losing message


Spectator message (for anyone who watches in spectator mode)

**Comment by HazryG** [comment]
Obviously the winning team changes if red team wins (or another team *cough* infection)

**Comment by tjhubz** [comment]
I feel like it would look better if it wasn't centered, and instead to the left.

**Comment by lukechatton** [comment]
Was this bundled in draem's merge a while ago? If so, please close :)

**Pull request closed without merging**
