### PR TITLE
Fix some bugs and broken effects

### PR DESCRIPTION
**Pull request by MatrixTunnel**

### CODE REVIEW

**Comment by tjhubz** [comment]
Does this fix CTW scoreboards?

**Comment by MatrixTunnel** [comment]
When picking up wool? Yes it does

**Comment by tjhubz** [comment]
No, currently the scoreboard is completely incorrect, it shows collected when not collected, shows nothing when it is, etc.

**Comment by MatrixTunnel** [comment]
Yea, it's fixed with this PR

**Pull request merged**
